### ISSUE TITLE
Read processingMCP.xml from external storage

### ISSUE THREAD

**Issue by mjaddis** [JiscRDSS/rdss-archivematica-automation-tools#1]
The processingMCP.xml file used by the automation tools should be read from external storage so that the config can be updated easily by external applications.   Ideally, the processingMCP.xml files created by Archivematica should be shared with the automation tools via common external storage, e.g. the NFS server, so that if the user updates the config in Archivematica then it will automatically get picked up by the automation tools.  In the case of the RDSS MVP this would be automatedProcessingMCP.xml

**Comment by mjaddis** [comment]
When starting work on this or when there is a fix ready for Jisc to deploy, please update the corresponding JIRA issue: https://jiscdev.atlassian.net/browse/RDSSARK-227

**Comment by lower29** [comment]
We already allow the Processing XML to be configurable, via the `AM_TOOLS_TRANSFER_PROCESSING_XML` environment variable. There is an assumption that this file is located within the `sharedMicroServiceTasksConfigs/processingMCPConfigs` folder within the folder defined by the `AM_SHARED_DIR` environment variable, which by default is `/var/archivematica/sharedDirectory` (in a docker-compose deployment this is mapped to the `archivematica_pipeline_data` external volume, as shown in the example in the README for this project).

So we're already using a file from the main Archivematica config location, and this is copied to the automation-tools host as part of the initial setup in `setup.sh`. I think however, this is perhaps where the problem lies: because we create a new copy of the XML file, if it's changed in Archivematica or elsewhere then these changes aren't reflected in the local copy.

Therefore, if I'm understanding the problem correctly, this could perhaps be solved by symlinking to the XML file rather than copying, thereby ensuring the file that the automation tools use remains current.

Have I understood the problem correctly?

**Comment by mjaddis** [comment]
Yep, correct - if the processing config (automatedProcessingMCP.xml) is updated via Archivematica then we want this picked up and applied by the automation tools.    As you say, at the moment the container makes a copy of this file when the automation tool is first run (IIRC - transfer.sh calls setup.sh).

**Comment by lower29** [comment]
Okay then, sounds like a symlink will do the job then - unless there's some technical reason why that won't/can't work.

**Comment by lower29** [comment]
This has been fixed by https://github.com/JiscRDSS/rdss-archivematica-automation-tools/pull/7, closing.
